### ISSUE TITLE
Provide functionality similar to Spring Boot's BeanTypeRegistry

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-framework#23056]
Spring Boot currently has an internal class called [`BeanTypeRegistry`](https://github.com/spring-projects/spring-boot/blob/e481eccd577fd7dcee9c02c20fd10c60b762bf7d/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/BeanTypeRegistry.java#L68) that is used by `@ConditionalOnBean` and `@ConditionalOnMissingBean`. We've have a [recent issue](https://github.com/spring-projects/spring-boot/pull/16615#discussion_r278441383) where we need something similar, but rather than make it public in Spring Boot it might be better if Spring Framework could offer methods that we could use.

What we specifically need is a way to predict the bean type in a way that's very fast to call during condition evaluation and doesn't cause any early initialization of any beans (including `FactoryBeans`).

---

After some analysis, I'm going to split this issue up into a number of smaller parts:
- [x] Add missing ResolvableType variants of getBeanNamesForType (#23335)
- [x] Retain merged bean definition caches during post processing (#23336)
- [x]  Cache isFactoryBean detection (#23337)
- [x] Consider generics when predicting FactoryBean types (#23338)
- [x] Add attribute support for FactoryBean bean definitions (#23339)
- [x] Use static final constants for common zero length arrays (#23340)

**Comment by tkvangorder** [comment]
@philwebb Any movement on this issue? I could take a stab at PR for this, but I would need some guidance on which package to move the code and/or what to rename the `BeanTypeRegistry` such that it conforms to how things are organized in the core Spring framework.

**Comment by philwebb** [comment]
Thanks for the offer @tkvangorder but I'm already in the middle of trying various changes. We won't be able to migrate `BeanTypeRegistry` as it is, instead we need to look at changing some of the core `BeanFactory` implementations. Unfortunately that's quite a complex part of the codebase so it's taking some time.

**Comment by tkvangorder** [comment]
yep, not for the faint of heart. 8) Make sense, thank you!
